import BenzelProblem6Kernel.PublicationRoot

/-! # Publication-root theorem map -/

#check BenzelProblem6Kernel.publication_terminal_support_tree
#check BenzelProblem6Kernel.publication_terminal_word_empty
#check BenzelProblem6Kernel.publication_conwayLagarias_stone_count
#check BenzelProblem6Kernel.publication_literal_path_equivalence
#check BenzelProblem6Kernel.publication_literal_path_equivalence_target
#check BenzelProblem6Kernel.publication_main_theorem

#check BenzelProblem6Kernel.manuscript_thm_main
#check BenzelProblem6Kernel.manuscript_eq_ballot_form
#check BenzelProblem6Kernel.manuscript_lem_tile_counts
#check BenzelProblem6Kernel.manuscript_eq_owner_coordinates
#check BenzelProblem6Kernel.manuscript_owner_anchor_injective
#check BenzelProblem6Kernel.manuscript_lem_owner_simplex_meets
#check BenzelProblem6Kernel.manuscript_lem_owner_simplex_partition
#check BenzelProblem6Kernel.manuscript_eq_cell_energy
#check BenzelProblem6Kernel.manuscript_lem_energy_table_values
#check BenzelProblem6Kernel.manuscript_lem_energy_table_profiles
#check BenzelProblem6Kernel.manuscript_lem_energy_table_directions
#check BenzelProblem6Kernel.manuscript_prop_energy_rigidity
#check BenzelProblem6Kernel.manuscript_prop_Y_bijection
#check BenzelProblem6Kernel.manuscript_lem_independent_arms_positive_factors
#check BenzelProblem6Kernel.manuscript_lem_independent_arms_negative_factors
#check BenzelProblem6Kernel.manuscript_lem_independent_arms_positive_count
#check BenzelProblem6Kernel.manuscript_lem_independent_arms_negative_count
#check BenzelProblem6Kernel.manuscript_eq_Pxyz
#check BenzelProblem6Kernel.manuscript_eq_Qxyz
#check BenzelProblem6Kernel.manuscript_eq_QoverP
#check BenzelProblem6Kernel.manuscript_prop_generating_functions
#check BenzelProblem6Kernel.manuscript_eq_Pgf
#check BenzelProblem6Kernel.manuscript_eq_Qgf
#check BenzelProblem6Kernel.manuscript_eq_Ygf
#check BenzelProblem6Kernel.manuscript_eq_constant_term
