import BenzelProblem6Kernel.PublicationRoot

/-! # Axiom receipts for every unique endpoint in `ManuscriptFormulaMap.lean` -/

#print axioms BenzelProblem6Kernel.literalTilingToPathModel_pathModelToLiteralTiling
#print axioms BenzelProblem6Kernel.manuscript_eq_ballot_form
#print axioms BenzelProblem6Kernel.manuscript_eq_cell_energy
#print axioms BenzelProblem6Kernel.manuscript_eq_constant_term
#print axioms BenzelProblem6Kernel.manuscript_eq_owner_coordinates
#print axioms BenzelProblem6Kernel.manuscript_eq_Pgf
#print axioms BenzelProblem6Kernel.manuscript_eq_Pxyz
#print axioms BenzelProblem6Kernel.manuscript_eq_Qgf
#print axioms BenzelProblem6Kernel.manuscript_eq_QoverP
#print axioms BenzelProblem6Kernel.manuscript_eq_Qxyz
#print axioms BenzelProblem6Kernel.manuscript_eq_Ygf
#print axioms BenzelProblem6Kernel.manuscript_lem_energy_table_directions
#print axioms BenzelProblem6Kernel.manuscript_lem_energy_table_profiles
#print axioms BenzelProblem6Kernel.manuscript_lem_energy_table_values
#print axioms BenzelProblem6Kernel.manuscript_lem_independent_arms_negative_factors
#print axioms BenzelProblem6Kernel.manuscript_lem_independent_arms_negative_count
#print axioms BenzelProblem6Kernel.manuscript_lem_independent_arms_positive_factors
#print axioms BenzelProblem6Kernel.manuscript_lem_independent_arms_positive_count
#print axioms BenzelProblem6Kernel.manuscript_lem_owner_simplex_meets
#print axioms BenzelProblem6Kernel.manuscript_lem_owner_simplex_partition
#print axioms BenzelProblem6Kernel.manuscript_lem_tile_counts
#print axioms BenzelProblem6Kernel.manuscript_owner_anchor_injective
#print axioms BenzelProblem6Kernel.manuscript_prop_energy_rigidity
#print axioms BenzelProblem6Kernel.manuscript_prop_generating_functions
#print axioms BenzelProblem6Kernel.manuscript_prop_Y_bijection
#print axioms BenzelProblem6Kernel.manuscript_thm_main
#print axioms BenzelProblem6Kernel.manuscriptPositiveConstantTermSeries
#print axioms BenzelProblem6Kernel.negative_arms_one_two_meet_only_at_sink
#print axioms BenzelProblem6Kernel.negative_arms_two_zero_meet_only_at_sink
#print axioms BenzelProblem6Kernel.negative_arms_zero_one_meet_only_at_sink
#print axioms BenzelProblem6Kernel.negative_labelOne_prefix_bounds
#print axioms BenzelProblem6Kernel.negative_labelTwo_prefix_bounds
#print axioms BenzelProblem6Kernel.negative_labelZero_prefix_bounds
#print axioms BenzelProblem6Kernel.nonempty_literalYPathData
#print axioms BenzelProblem6Kernel.pathModelToLiteralTiling_literalTilingToPathModel
#print axioms BenzelProblem6Kernel.positive_arms_one_two_meet_only_at_sink
#print axioms BenzelProblem6Kernel.positive_arms_two_zero_meet_only_at_sink
#print axioms BenzelProblem6Kernel.positive_arms_zero_one_meet_only_at_sink
#print axioms BenzelProblem6Kernel.positive_labelOne_prefix_bounds
#print axioms BenzelProblem6Kernel.positive_labelTwo_prefix_bounds
#print axioms BenzelProblem6Kernel.positive_labelZero_prefix_bounds
#print axioms BenzelProblem6Kernel.positiveGoodConstantTermCoefficient_eq
#print axioms BenzelProblem6Kernel.positiveGoodConstantTermLevel_eq
